# The NumPy.Random Python Package  
***
## Author: Fionn McCarthy - G00301126
***
![xplotoutput](numpy_image.png) 
***
## Introduction and Backgroud of NumPy.Random Package
Firstly, I will given a short background on the NumPy library, as this is where the NumPy.Radnom module derives from. NumPy is a python based library that contains multi-dimensional array objects known as **ndarray** and a number of functions for performing mathematical and logical operations on these arrays, it's name is short notation for 'Numerical Python' [1]. It is one of the most useful libraries in python for it's ability to perform numerical computation so quickly. 

NumPy.Random is a module within the NumPy library which is utilized for random sampling, the functions within this module are for generating random numbers. The package contains functions that allows for simple random data generation, permutation and distribtution functions and random generator functions [2]. The random number routines within the NumPy.Random package produce pseudo random numbers by utilizing both the **BitGenerator** in order to produce sequences and then the **Generator** to use the sequences that have been created in order to sample from the different statistical distributions [3]. In order to generate random numbers a computer needs to follow a certain algorithm or a particular set of rules or instructions, when random numbers are generated by computers using threse instrcutions or algorithms the numbers are called pseudo-random [5]. The package contains a collection of funtions that helps to produce arrays of pseudo-random numbers with the various different probability distributions. This brilliant package enables the user to generate numbers at random within different ranges with the use of it's different functions, it also enables the user to seelct teh different probability distribution they required the data to be produced in. This can be compared to some real life situations such as flipping a coin and how the results of a thousand coin tosses can be generated and examined, or how to generate the outcomes of the roll of a dice or of two dice and then generating the results of rolling these dice a thousand times in order to investigate these results. 

The main aims of the package are random number genration, random processes such as shuffiling and permutating and also to enable random selection of items from lists and sequences. 

In [1]:
# Import libraries utilized in the jupyter notebook

import numpy as np               # working with arrays and computation
import matplotlib.pyplot as plt  # plotting functions
import pandas as pd              # working with dataframes 
import seaborn as sns            # data visualisation

# allows for inline plotting in jupyter notebook 
%matplotlib inline

# Change style sheet to seaborn
plt.style.use('seaborn')

The Random Number Generator

In [2]:
# construcitng the random number generator with the default BitGenerator (PCG64) and stores it in the rng object 
rng = np.random.default_rng()

## Simple Random Data 
The NumPy.Random package has the following four functions for simpled random data, the below image displays the parameters/arguments eahc function takes and the output of these functions. 
![xplotoutput](Simple_Random_Data.png) 

### random.integers() 
Function used to generate arrays of random integers between the given interval

In [3]:
# The below shows a 1x8 array of random integers in the interval 0 to 2
rng.integers(2, size=8)

array([0, 1, 1, 0, 0, 1, 1, 0], dtype=int64)

In [4]:
# The below shows a 1x8 array of random integers in the interval 0 to 2, notice how this time 2 is included in teh intervak of random numbers to choose from, 
# when you set the endpoint to true endpoint=True the upper bound is included. So the number 2 wil appear as shown below. 
rng.integers(2, size=8, endpoint=True)

array([0, 0, 1, 1, 0, 0, 2, 2], dtype=int64)

In [5]:
# The below shows a 2x4 array where teh size of teh array is set by the size=(2, 4) parameter here,
# the upper bound is set to 5 here but the endpoint is not specified to will be set to default (false) and will only show integers between 0 and 4
rng.integers(5, size=(2, 4))

array([[3, 1, 2, 1],
       [3, 3, 2, 4]], dtype=int64)

random.random() - This function a random value between 0 and 1

In [6]:
x = rng.random()
print(x)

0.493858866805166


random.choice

random.bytes

## Permutations Functions. 

random.shuffle

random.permutation

random.permuted

## Distributions Functions.

## Seeds. 

## References
1. https://www.mygreatlearning.com/blog/python-numpy-tutorial/ 04/11/2021 
2. https://www.javatpoint.com/numpy-random 09/11/2021
3. https://numpy.org/doc/stable/reference/random/index.html 04/11/2021
4. https://numpy.org/doc/stable/reference/random/generator.html important doc 
5. https://www.w3schools.com/python/numpy/numpy_random.asp 